language: go

# https://github.com/GoogleCloudPlatform/golang-samples/blob/master/.travis.yml
before_cache:
  - rm -rf $GOPATH/src/github.com/kjk/blog
  - rm -rf $GOPATH/pkg/**/github.com/kjk/blog

branches:
  only:
    - master

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
  - ./s/travis_install.sh

script:
  - ./s/travis_build.sh
